spring.application.name=groundschool

spring.docker.compose.lifecycle-management=start_only

spring.sql.init.mode=always

spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.externalization.enabled=true

spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase

spring.rabbitmq.password=secret
spring.rabbitmq.username=myuser